[default]
JSON_AS_ASCII = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
SESSION_REFRESH_EACH_REQUEST = true
COLOR_THEME = "is-primary"
APP_NAME = "OralSin"
FAV_ICO="img/oralsin/favicon.ico"
IMG_LOGO="img/oralsin/logo.png"


EXTENSIONS = [
    "timesheet.ext.api:init_app",
    "timesheet.ext.db:init_app",
    "timesheet.ext.site:init_app",
    "timesheet.ext.auth:init_app",
    "timesheet.ext.admin:init_app",
    "timesheet.ext.cli:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "mysql+mysqlconnector://root:MySql2019!@localhost:3306/timesheet"

[production]
SQLALCHEMY_POOL_RECYCLE = 100
SQLALCHEMY_DATABASE_URI = "mysql+mysqlconnector://b846f101070bdb:4ea95c24@us-cdbr-east-02.cleardb.com/heroku_4c9d2a4e8dd9512"
